server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://106.52.105.41:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mysql_school
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  type-aliases-package: com.ccty.noah.domain.database
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  SMS:
    accessKeyId: LTAI4G2C2oGF9LjkVBsLe5V9
    accessSecret: 7qssSp5jDPmRQvyHzYHSu3HPxSPZAp
    singleName: 校V家
    templateCode: SMS_201717216