server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://106.52.105.41:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: mysql_school
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 1000MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  type-aliases-package: com.ccty.noah.domain.database
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  SMS:
    accessKeyId: LTAI4G2C2oGF9LjkVBsLe5V9
    accessSecret: 7qssSp5jDPmRQvyHzYHSu3HPxSPZAp
    singleName: 校V家
    templateCode: SMS_201717216

tengxun:
  accessKey: AKIDnZeWAdjci5GDuMtVGm34qN1OURia3bja
  secretKey: vmQowsXv50lFVWUBK5dvxjJZrzrUYP2U
  bucket: ap-nanjing
  bucketName: test-1300839768
  path: http://test-1300839768.cos.ap-nanjing.myqcloud.com/
